### ISSUE TITLE
User Signup Form

### ISSUE THREAD

**Issue by BallerHat** [Jayd-H/UniSphere#32]
## Description
-	Users can create an account with a unique username. This account will be created with basic user information (i.e. username, display name, interests(?), bio(?))
-	Users can create an account with a secure password.

## Tasks 

- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #37

## NFRs/DoD

- [x] Can users access the signup page?
- [x] Are users told when a username has been used?
- [x] Can users only use certain characters in the text field?
- [x] Are users told about the password requirements?
- [x] Are there checks that the password meets the requirements?
- [x] Is the user prevented from submitting invalid data? 

## Priority

- Must have; no viable product without.
- Low Risk; unlikely to be subject to change, good dev knowledge, well-understood requirement.
- Other areas rely on this being completed.
