### ISSUE TITLE
User Login Form

### ISSUE THREAD

**Issue by BallerHat** [Jayd-H/UniSphere#39]
## Description

-	Users can log in with their unique username and password.
-	Users can access and modify their account information.
-	Users cannot login or modify data without secure password.

## Tasks

- [x] #40
- [x] #41
- [x] #42
- [x] #43

## NFRs/DoD

- [x] Can users access the login page?
- [x] Are users informed when they submit invalid details?
- [x] Are users informed when they enter invalid characters?
- [x] Are users prevented from submitting the form with invalid characters?

## Priority

- Must have; no viable product without.
- Low Risk; unlikely to be subject to change, good dev knowledge, well-understood requirement.
- Other areas rely on this being completed.
