### ISSUE TITLE
Signup Handler

### ISSUE THREAD

**Issue by BallerHat** [Jayd-H/UniSphere#44]
## Description
Handles post from signup page/url, validates data (ensures no invalid characters, already used username, and password meets requirements), and enters the information into the database.

## Tasks

- [x] #45
- [x] #46
- [x] #47
- [x] #48
- [x] #49

## NFRs/DoD

- [x] Does event trigger from form post?
- [x] Can handler access form data?
- [x] If invalid characters in form, will handler catch?
- [x] If username not unique, will handler catch?
- [x] Is the data successfully added to the database?

## Priority

- Must have; no viable product without;
- Medium risk; relies on continuity between frontend and databases implementations, must inquire!
- Relies on a database implementation beforehand.
