### ISSUE TITLE
Modifying User Info

### ISSUE THREAD

**Issue by BallerHat** [Jayd-H/UniSphere#91]
## Description
Users can access a page where they can view and modify their account information. 

This includes:
- Changing their name
- Changing their password
- Adding/changing their profile picture
- Viewing what societies they are in

## Tasks
- [ ] Users can navigate to a 'User Settings' page
- [ ] User settings page presents a field for changing the user's name
- [ ] Input validation for user settings name field
- [ ] Posting name field from user settings to the backend
- [ ] User settings page presents a field for changing the user's password
- [ ] Input validation for user settings password field
- [ ] Posting password field from user settings to the backend
- [ ] User settings page page presents a preview of the user's profile picture
- [ ] User can use the preview of their profile picture to upload a new one
- [ ] Functionality for uploading a new profile picture
- [ ] User settings page presents users with a list of societies they have joined

## NFRs/Acceptance Criteria
- [ ] Can users access the user settings page?
- [ ] Is there a field where users can enter a new username?
- [ ] Is there a field where users can enter a new password?
- [ ] Are users warned when entering invalid characters?
- [ ] Are users prevented from submitting data with invalid characters?
- [ ] Can the user see their current profile picture?
- [ ] Can users upload a profile picture?
- [ ] Are client-side limits in place for the upload/file?
- [ ] Are users informed of the limits for the upload?
- [ ] Can users see a list of societies they have joined?

## Definition of Done
- [ ] Each Task Has Been Peer Reviewed
- [ ] Acceptance Test Passed
- [ ] Unit Tests Written
- [ ] All Unit Tests Passed
- [ ] Smoke Test Passed

## Priority
- Must have; integral to user experience.
- Low/Medium Risk; functionality for all but the profile picture should be easy.
